### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by leman-kg** [bautistaj/postman-to-markdown#10]
```
/usr/local/lib/node_modules/postman-to-markdown/src/util/index.js:68
  if (url?.query) {
          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postman-to-markdown/src/index.js:6:50)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by truth1024** [comment]
I have the same problem

**Comment by daeseokyoun** [comment]
Optional chaining(`?.`) is currently not supported in Node.js version 13 and below. 

find this in stackoverflow: https://stackoverflow.com/questions/59574047/how-to-use-optional-chaining-in-node-js-12
